spring:
  application:
    name: alien_letter_service

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .xml
    mode: XML

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: PUBLIC

letter_file:
  path: ${LETTER_FILE_PATH:src/main/resources/templates/alien_letter.xml}